------ Create table  ------
-- connect to the database using SQLTools in vscode before doing the following --
-- CREATE TABLE person (
--     id BIGSERIAL NOT NULL PRIMARY KEY,
--     first_name VARCHAR(50) NOT NULL,
--     last_name VARCHAR(50) NOT NULL,
--     gender VARCHAR(7) NOT NULL,
--     email VARCHAR(150) NOT NULL
-- );
-- add some recrod --
-- INSERT INTO person
-- VALUES (
--         1,
--         'John',
--         'Smith',
--         'male',
--         'john.smith@gmail.com'
--     ),
--     (2, 'Sarah', 'Jones', 'female', 'sarah.jones@company.com');
-- later data type --
ALTER TABLE person
ALTER COLUMN email DROP NOT NULL;